## Golden tests: boney's sampled bone transforms vs a reference oracle.
##
## Oracle source: tools/oracle/expected.json, generated by tools/oracle/emit.js —
## a standalone Node reference implementation of DragonBones 5.x linear keyframe
## sampling and matrix-compose world propagation (NOT the dragonBones npm runtime;
## see tools/oracle/README.md). It uses true matrix multiplication for world
## propagation, whereas boney uses DbTransform-space accumulation (propagate.nim).
## The two agree for the Dragon fixture because the arm bone has no parent
## scale/skew — the identity 2×2 case where both formulations give the same result.
##
## The oracle samples the "Dragon" / "idle" animation at frames 0, 6, 12, 18, 24
## (t = 0.0, 0.25, 0.5, 0.75, 1.0 seconds at frameRate=24).
##
## Epsilon is 1e-4: float64 (JS oracle) vs float32 (boney) gives worst-case
## divergence ~1e-6 for trig values; 1e-4 provides headroom for host/ARM drift.

import std/[unittest, strutils, os]
import vmath
import dragonbones/model/model
import dragonbones/parse/armature
import dragonbones/anim/sample
import dragonbones/anim/propagate

const Eps = 1e-4'f32

var propagateScratch: seq[DbTransform]

# ── Helpers ───────────────────────────────────────────────────────────────────

proc approxEq(a, b: float32): bool = abs(a - b) < Eps

proc checkMatrix(m: Mat3; expA, expB, expC, expD, expTx, expTy: float32) =
  ## Verify the 2D affine matrix using the DragonBones/Flash {a,b,c,d,tx,ty} convention:
  ##   a = col0[0] (scX*cos(skY)), b = col0[1] (scX*sin(skY))
  ##   c = col1[0] (-scY*sin(skX)), d = col1[1] (scY*cos(skX))
  ##   tx = col2[0], ty = col2[1]
  ## Tested via vector transforms to avoid vmath m[i] indexing (returns Vec3 column).
  let pos = m * vec3(0.0'f32, 0.0'f32, 1.0'f32)
  let xa  = m * vec3(1.0'f32, 0.0'f32, 0.0'f32)
  let ya  = m * vec3(0.0'f32, 1.0'f32, 0.0'f32)
  check approxEq(pos.x, expTx); check approxEq(pos.y, expTy)
  check approxEq(xa.x, expA);   check approxEq(xa.y, expB)
  check approxEq(ya.x, expC);   check approxEq(ya.y, expD)

# ── Fixture loaded once at module level ───────────────────────────────────────

let fixturePath = currentSourcePath().parentDir() / ".." / "fixtures" / "sample" / "dragon_ske.json"
let gDb = parseDragonBones(readFile(fixturePath))

let gArm = block:
  var a: ArmatureData
  for arm in gDb.armatures:
    if arm.name == "Dragon": a = arm; break
  a

let gAnim = block:
  var an: AnimationData
  for anim in gArm.animations:
    if anim.name == "idle": an = anim; break
  an

proc go(arm: ArmatureData, anim: AnimationData, t: float32): seq[BoneState] =
  ## Sample animation at t seconds, propagate world transforms, return bones.
  var bones = newSeq[BoneState](arm.bones.len)
  var slots = newSeq[SlotState](arm.slots.len)
  sampleAnimation(anim, arm, t, bones, slots)
  propagateWorldTransforms(arm, bones, propagateScratch)
  bones

# ── Oracle comparison: frames 0, 6, 12, 18 ───────────────────────────────────
#
# The oracle was sampled with playTimes=0 (loop-forever). Frames 0–18 are
# unambiguously within the first play period; their expected values match
# boney's loop-forever semantics without adjustment.

suite "oracle — dragon idle frames 0–18":

  test "frame 0 / t=0.0: root identity matrix, arm world at (50, 0)":
    let bones = go(gArm, gAnim, 0.0'f32)
    ## root at origin, no rotation: identity
    checkMatrix(bones[0].worldMatrix, 1,0, 0,1, 0,0)
    ## arm rest pose x=50; world position (50, 0)
    checkMatrix(bones[1].worldMatrix, 1,0, 0,1, 50,0)

  test "frame 6 / t=0.25s: root 22.5°, arm at (46.19, 19.13)":
    let bones = go(gArm, gAnim, 0.25'f32)
    let c = 0.9238795'f32   # cos(22.5°)
    let s = 0.3826834'f32   # sin(22.5°)
    checkMatrix(bones[0].worldMatrix, c, s, -s, c, 0, 0)
    checkMatrix(bones[1].worldMatrix, c, s, -s, c, 46.19398'f32, 19.13417'f32)

  test "frame 12 / t=0.5s: root 45°, arm at (35.36, 35.36)":
    let bones = go(gArm, gAnim, 0.5'f32)
    let c = 0.7071068'f32   # cos(45°) = sin(45°)
    checkMatrix(bones[0].worldMatrix, c, c, -c, c, 0, 0)
    checkMatrix(bones[1].worldMatrix, c, c, -c, c, 35.35534'f32, 35.35534'f32)

  test "frame 18 / t=0.75s: root 67.5°, arm at (19.13, 46.19)":
    let bones = go(gArm, gAnim, 0.75'f32)
    let c = 0.3826834'f32   # cos(67.5°)
    let s = 0.9238795'f32   # sin(67.5°)
    checkMatrix(bones[0].worldMatrix, c, s, -s, c, 0, 0)
    checkMatrix(bones[1].worldMatrix, c, s, -s, c, 19.13417'f32, 46.19398'f32)

# ── Frame 24: hold at last keyframe (non-loop play) ──────────────────────────
#
# expected.json's frame-24 row captures the last-keyframe hold (rotation 90°).
# The SHIPPING animation uses playTimes=0 (loop-forever), where t=1.0 wraps to
# frame 0 — not 90°. To compare against the oracle's frame-24 value we must
# use a playTimes=1 copy: resolveFrame then clamps to frame 24 (the last kf)
# rather than wrapping. The "loop semantics" suite below tests the shipping
# (playTimes=0) boundary separately.

suite "oracle — frame 24 hold (playTimes=1)":

  test "t=1.0 / playTimes=1: root 90°, arm world at (≈0, 50)":
    var animOnce = gAnim
    animOnce.playTimes = 1
    let bones = go(gArm, animOnce, 1.0'f32)
    ## cos(90°) ≈ 0 in float32; sin(90°) = 1 exactly.
    checkMatrix(bones[0].worldMatrix, 0,1, -1,0, 0,0)
    let pos = bones[1].worldMatrix * vec3(0.0'f32, 0.0'f32, 1.0'f32)
    check approxEq(pos.x, 0.0'f32)   # 50*cos(90°) ≈ 0
    check approxEq(pos.y, 50.0'f32)  # 50*sin(90°) = 50

# ── Loop semantics at the boundary ───────────────────────────────────────────

suite "loop semantics":

  test "t=1.0 / playTimes=0: wraps to frame 0, same pose as t=0.0":
    ## With loop-forever, t=1.0 (24 frames) wraps back to frame 0.
    let bonesA = go(gArm, gAnim, 0.0'f32)
    let bonesB = go(gArm, gAnim, 1.0'f32)
    let vaXA = bonesA[0].worldMatrix * vec3(1.0'f32, 0.0'f32, 0.0'f32)
    let vaXB = bonesB[0].worldMatrix * vec3(1.0'f32, 0.0'f32, 0.0'f32)
    check approxEq(vaXA.x, vaXB.x)
    check approxEq(vaXA.y, vaXB.y)

  test "t=0.5 and t=1.5 give identical root rotation (second loop)":
    let b05 = go(gArm, gAnim, 0.5'f32)
    let b15 = go(gArm, gAnim, 1.5'f32)
    let v05 = b05[0].worldMatrix * vec3(1.0'f32, 0.0'f32, 0.0'f32)
    let v15 = b15[0].worldMatrix * vec3(1.0'f32, 0.0'f32, 0.0'f32)
    check approxEq(v05.x, v15.x)
    check approxEq(v05.y, v15.y)

  test "loop seam: t just below 1.0 resolves to near frame 24 (rotation near 90°)":
    ## Guards the loop seam neighborhood: at t slightly less than 1.0 the frame
    ## should still be inside [0, 24) approaching frame 24, not yet wrapped.
    let f = resolveFrame(gAnim, (23.99'f32 / 24.0'f32), gArm.frameRate)
    check f > 23.0'f32
    check f < 24.0'f32

  test "loop seam: t=1.0 exactly resolves to frame 0 (not frame 24)":
    ## Explicit convention pin: duration=24, playTimes=0, t=1.0 → frame 0.
    ## This documents the half-open [0, duration) semantic for loop-forever.
    check resolveFrame(gAnim, 1.0'f32, gArm.frameRate) == 0.0'f32

# ── frames↔seconds conversion ─────────────────────────────────────────────────

suite "frames<->seconds":

  test "t=0.0s resolves to frame 0":
    check approxEq(resolveFrame(gAnim, 0.0'f32, gArm.frameRate), 0.0'f32)

  test "t=0.25s resolves to frame 6 at frameRate=24":
    check approxEq(resolveFrame(gAnim, 0.25'f32, gArm.frameRate), 6.0'f32)

  test "t=0.5s resolves to frame 12 at frameRate=24":
    check approxEq(resolveFrame(gAnim, 0.5'f32, gArm.frameRate), 12.0'f32)

  test "t=0.75s resolves to frame 18 at frameRate=24":
    check approxEq(resolveFrame(gAnim, 0.75'f32, gArm.frameRate), 18.0'f32)

  test "zero-duration animation: resolveFrame returns 0 regardless of t":
    var zeroAnim = gAnim
    zeroAnim.duration = 0
    check resolveFrame(zeroAnim, 0.5'f32, gArm.frameRate) == 0.0'f32

# ── Edge cases — empty timelines ───────────────────────────────────────────────

suite "edge cases — empty timelines":

  test "arm has no animation timeline: local transform stays at rest pose":
    ## The dragon fixture has no arm bone animation — only root is animated.
    ## sampleAnimation must initialise arm from its BoneData rest pose (x=50).
    let bones = go(gArm, gAnim, 0.25'f32)
    check approxEq(bones[1].localTransform.x,   50.0'f32)
    check approxEq(bones[1].localTransform.y,    0.0'f32)
    check approxEq(bones[1].localTransform.scX,  1.0'f32)
    check approxEq(bones[1].localTransform.scY,  1.0'f32)
    check approxEq(bones[1].localTransform.skX,  0.0'f32)

  test "animation with no bone timelines: all bones at rest pose":
    let emptyAnim = AnimationData(name: "empty", duration: 24, playTimes: 1)
    let bones = go(gArm, emptyAnim, 0.5'f32)
    ## root rest pose: identity (no transform in JSON, defaults applied)
    check approxEq(bones[0].localTransform.scX, 1.0'f32)
    check approxEq(bones[0].localTransform.scY, 1.0'f32)
    check approxEq(bones[0].localTransform.skX, 0.0'f32)
    ## arm rest pose: x=50
    check approxEq(bones[1].localTransform.x, 50.0'f32)

  test "empty animation: no crash, bones are valid":
    ## Completely empty animData: duration=0, no timelines.
    let emptyAnim = AnimationData(name: "empty")
    var bones = newSeq[BoneState](gArm.bones.len)
    var slots  = newSeq[SlotState](gArm.slots.len)
    sampleAnimation(emptyAnim, gArm, 0.0'f32, bones, slots)
    propagateWorldTransforms(gArm, bones, propagateScratch)
    ## Bones should be finite (not NaN/Inf).
    let v = bones[0].worldMatrix * vec3(0.0'f32, 0.0'f32, 1.0'f32)
    check not isNan(v.x)
    check not isNan(v.y)

# ── Edge cases — NaN guard via tkStepped ──────────────────────────────────────

suite "edge cases — NaN guard":

  test "tkStepped (tweenEasing=NaN) tween: holds kf0 value, output is finite":
    ## A tkStepped curve always returns t=0, so lerp reads the FIRST keyframe
    ## value for the entire duration — no NaN ever enters the transform.
    ## This is the parsed form of JSON tweenEasing: null or NaN.
    let steppedCurve = TweenCurve(kind: tkStepped)
    let tl = Timeline(kind: tlBoneRotate, name: "root",
                      rotateKFs: @[
                        BoneRotateKF(base: KeyframeBase(frame: 0, duration: 24,
                                                         curve: steppedCurve),
                                     rotate: 45.0'f32),
                        BoneRotateKF(base: KeyframeBase(frame: 24, duration: 0),
                                     rotate: 90.0'f32)])
    let steppedAnim = AnimationData(name: "stepped", duration: 24, playTimes: 1,
                                    timelines: @[tl])
    let bones = go(gArm, steppedAnim, 0.5'f32)
    ## tkStepped holds kf0 (rotate=45°) for the entire duration.
    let xa = bones[0].worldMatrix * vec3(1.0'f32, 0.0'f32, 0.0'f32)
    check not isNan(xa.x)
    check not isNan(xa.y)
    ## xa ≈ (cos(45°), sin(45°))
    check approxEq(xa.x, 0.7071068'f32)
    check approxEq(xa.y, 0.7071068'f32)

  test "zero-scale bone (degenerate): world matrix finite, no NaN propagation to child":
    ## scX=0 produces a degenerate (non-invertible) matrix.
    ## Forward propagation must still be finite; only inverse operations would be undefined.
    let zeroScaleTl = Timeline(kind: tlBoneScale, name: "root",
                               scaleKFs: @[
                                 BoneScaleKF(base: KeyframeBase(frame: 0, duration: 0),
                                             scX: 0.0'f32, scY: 1.0'f32)])
    let zeroAnim = AnimationData(name: "zerscale", duration: 1, playTimes: 1,
                                 timelines: @[zeroScaleTl])
    let bones = go(gArm, zeroAnim, 0.0'f32)
    ## child (arm) inherits scale — arm world matrix must be finite
    let childPos = bones[1].worldMatrix * vec3(0.0'f32, 0.0'f32, 1.0'f32)
    check not isNan(childPos.x)
    check not isNan(childPos.y)

# ── Missing subtextures: slot display index is stored, not validated ──────────
#
# The sampling layer is deliberately decoupled from atlas/texture data.
# A displayIndex pointing beyond the slot's display list is stored as-is;
# the renderer validates it against atlas data at draw time. This satisfies
# the "missing subtextures handled" acceptance criterion: sampling never
# crashes on unresolvable display indices.

suite "edge cases — missing subtextures (display index)":

  test "out-of-range displayIndex: no crash, index stored verbatim":
    let oobTl = Timeline(kind: tlSlotDisplay, name: "root_slot",
                         displayKFs: @[
                           SlotDisplayKF(base: KeyframeBase(frame: 0, duration: 24),
                                         displayIndex: 99)])
    let oobAnim = AnimationData(name: "oob", duration: 24, playTimes: 1,
                                timelines: @[oobTl])
    var bones = newSeq[BoneState](gArm.bones.len)
    var slots  = newSeq[SlotState](gArm.slots.len)
    sampleAnimation(oobAnim, gArm, 0.5'f32, bones, slots)
    ## Sampling stores the index without bounds-checking; renderer's responsibility.
    check slots[0].displayIndex == 99

  test "displayIndex -1 (DisplayIndexHidden): slot hidden with no crash":
    let hideTl = Timeline(kind: tlSlotDisplay, name: "arm_slot",
                          displayKFs: @[
                            SlotDisplayKF(base: KeyframeBase(frame: 0, duration: 24),
                                          displayIndex: DisplayIndexHidden)])
    let hideAnim = AnimationData(name: "hide", duration: 24, playTimes: 1,
                                 timelines: @[hideTl])
    var bones = newSeq[BoneState](gArm.bones.len)
    var slots  = newSeq[SlotState](gArm.slots.len)
    sampleAnimation(hideAnim, gArm, 0.5'f32, bones, slots)
    check slots[1].displayIndex == DisplayIndexHidden

# ── Parse: version field accessible ──────────────────────────────────────────

suite "parse — version field":

  test "version string is non-empty after parse":
    check gDb.version.len > 0

  test "fixture version is in DragonBones 5.5–5.7 range":
    let parts = gDb.version.split('.')
    check parts.len >= 2
    check parts[0] == "5"
    let minor = parseInt(parts[1])
    check minor in [5, 6, 7]

  test "compatibleVersion is non-empty":
    check gDb.compatibleVersion.len > 0
